# Generated by Django 3.2.9 on 2021-12-02 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='type',
            new_name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
